### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by vzavala** [Argonne-National-Laboratory/DSP#14] opened 2017-07-12 14:23 UTC
vzavala@krylov64:/opt/DSP/examples/farmer$ julia farmer_run.jl 
ERROR: LoadError: LoadError: UndefVarError: dsp not defined
Stacktrace:
 [1] freeModel(::Dsp.DspCInterface.DspModel) at /home/vzavala/.julia/v0.6/Dsp/src/DspCInterface.jl:18
 [2] JuMP.Model(::Int64) at /home/vzavala/.julia/v0.6/Dsp/src/Dsp.jl:34
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /opt/DSP/examples/farmer/farmer_model.jl, in expression starting on line 23
while loading /opt/DSP/examples/farmer/farmer_run.jl, in expression starting on line 6
error in running finalizer: UndefVarError(var=:dsp)

**Comment by jalving** [comment] 2017-07-12 16:59
This is a breaking change from julia v0.5 to v0.6.  The following sample will reproduce the error in julia v0.6.

```Julia
using JuMP
using Dsp
m = Model(3) # a Dsp extended JuMP model
```
ERROR: UndefVarError: dsp not defined
Stacktrace:
 [1] freeModel(::Dsp.DspCInterface.DspModel) at /home/jordan/.julia/v0.6/Dsp/src/DspCInterface.jl:19
 [2] JuMP.Model(::Int64) at /home/jordan/.julia/v0.6/Dsp/src/Dsp.jl:34

It's throwing an error at the ccall with "freeModel", but I haven't figured out where the 'dsp not defined' is coming from yet.

**Comment by kibaekkim** [comment] 2017-07-12 18:18
@jalving You are right. This is very specific to v0.6 and most likely a bug from Julia v0.6. I could also reproduce the error in v0.6. But, it works fine in v0.5. The issue seems that the macro in a function does not recognize the argument which is also the function argument.

@vzavala Can you try it in v0.5?

**Comment by jalving** [comment] 2017-07-12 20:06
@kibaekkim Is this an escaping issue?  The following works for both v0.5 and v0.6:
```Julia
macro dsp_ccall(func, args...)
    @static if is_unix()
        return esc(quote
            ccall(($func, "libDsp"), $(args...))
        end)
    end
    @static if is_windows()
        return esc(quote
            ccall(($func, "libDsp"), stdcall, $(args...))
        end)
    end
end
```
I think since dsp.p is passed from a different module (Dsp.jl), the macro loses the reference when it evaluates inside DspCInterface.jl.  

I can make a pull request if you're satisfied with the change.

**Comment by kibaekkim** [comment] 2017-07-13 14:14
@jalving Thank you. It works for both. Please feel free to request a pull request and close the issue.

**Comment by kibaekkim** [comment] 2017-07-13 19:50
kibaekkim/Dsp.jl@69e1eae

**Closed by kibaekkim** 2017-07-13 19:50 UTC
