### ISSUE TITLE
./lib/libooqpmehrotra.a(MehrotraSolver.o): Relocation R_X86_64_32S can not be used against `_ZTV14MehrotraSolver 'when a shared object is made; recompile with -fPIC

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#20] opened 2017-12-14 16:15 UTC
hello I do not know what to do to repair the problem

[100%] Linking CXX shared library libDsp.so
/usr/bin/ld: ../lib/libooqpmehrotra.a(MehrotraSolver.o): no se puede usar la reubicación R_X86_64_32S contra `_ZTV14MehrotraSolver' cuando se hace un objeto compartido; recompile con -fPIC
../lib/libooqpmehrotra.a: error adding symbols: Valor erróneo
collect2: error: ld returned 1 exit status
src/CMakeFiles/Dsp.dir/build.make:1445: fallo en las instrucciones para el objetivo 'src/libDsp.so'
make[2]: *** [src/libDsp.so] Error 1
CMakeFiles/Makefile2:296: fallo en las instrucciones para el objetivo 'src/CMakeFiles/Dsp.dir/all'
make[1]: *** [src/CMakeFiles/Dsp.dir/all] Error 2
Makefile:129: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

Thank you

**Comment by kibaekkim** [comment] 2017-12-14 16:23
@Esnilg: It looks like the issue is related to linking. Can you give me more information about your machine and how you compiled the codes?

It would also be great if you can translate the message in English.

**Comment by Esnilg** [comment] 2017-12-14 16:46
Hi,

I'm working on an HP-Pavilion dv6-3151ss, Ubuntu 16.04 LTS, 
Intel® Core ™ i3 CPU M 370 @ 2.40GHz × 4, SO 64 bits.

Download OOQP, then use the following lines

MA27LIB = $ HOME / path / libma27.a
export MA27LIB

./configure
make
make install

Then from DSP / Build typing

cmake ..
make install

and in the end I get that error of recompiling -fPIC

**Comment by kibaekkim** [comment] 2017-12-14 21:13
You don't need to download and compile OOQP by yourself. If you use the command line in https://github.com/Argonne-National-Laboratory/DSP#download, if you follow the install instruction, the DSP installation will download and compile OOQP with the right compile flags. 

If you want to compile or use your own OOQP, then you should recompile OOQP with -fPIC flag.

**Comment by Esnilg** [comment] 2017-12-15 13:39
Thank you very much, I can to install libDsp.so library. I comment the steps I followed:

from the terminal:

git clone --recursive https://github.com/Argonne-National-Laboratory/DSP.git

Download to the folder DSP / extra / ma27-1.0.0

then inside the folder I made:

./configure 'CXXFLAGS = -fPIC' 'FFLAGS = -fPIC'

then download to the folder / extra / scipoptsuite-3.1.1

then inside the folder I made:

make scipoptlib SHARED = true READLINE = false GMP = false ZLIB = false

at the end in the root directory DSP / build

cmake ..
make install

and everything worked well

**Comment by kibaekkim** [comment] 2017-12-15 15:19
Great. Please feel free to create new issues in future. I am closing the issue now.

**Closed by kibaekkim** 2017-12-15 15:19 UTC
